# This workflow will build the project and upload the assets to the release.

name: Build Jar for Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
          cache: "pnpm"

      - name: Build with pnpm
        run: pnpm install && pnpm build

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*[!-all].jar
